name: first

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
     - run: date  
  
  windows:
    runs-on: windows-latest
    steps:
     - run: Get-Date
      
  macos:
    runs-on: macos-latest
    steps:
    -  run: date
    
  last:
    needs: [ubuntu, windows, macos]
    runs-on: windows-latest
    steps:
    - run : date 
      
